In [1]:
import pandas as pd
import numpy as np
import glob
import warnings as wn
import datetime as dt

In [2]:
yield_filenames=glob.glob(r'Solar_Power_Prediction'+"/*.xls")
alarm_filenames18=glob.glob(r'Alarm History/2018'+"/*.xlsx")
alarm_filenames19=glob.glob(r'Alarm History/2019'+"/*.xlsx")
alarm_filenames20=glob.glob(r'Alarm History/2020'+"/*.xlsx")
alarm_filenames21=glob.glob(r'Alarm History/2021'+"/*.xlsx")

In [3]:
def form_data(dataset,filenames):    
    for file in filenames:
        if filenames==yield_filenames:
            df=pd.concat(pd.read_excel(file,sheet_name=None,skiprows=16))
        else:
            df=pd.concat(pd.read_excel(file,sheet_name=None))
        dataset=dataset.append(df,ignore_index=True)
    dataset=dataset.sort_values(by='Date')
    return dataset
yield_dataset=pd.DataFrame()
yield_dataset=form_data(yield_dataset,yield_filenames)
#dataset['Date']=dataset['Date'].dt.strftime('%d/%m/%Y')
yield_dataset.head(25)

          Date  Total Yield [kWh]  Inverter 1 [kWh]
268 2018-11-13               67.7              67.7
269 2018-11-14              176.9             176.9
270 2018-11-15              183.5             183.5
271 2018-11-16              237.2             237.2
272 2018-11-17              240.5             240.5
273 2018-11-18              197.7             197.7
274 2018-11-19              159.3             159.3
275 2018-11-20              183.0             183.0
276 2018-11-21              228.5             228.5
277 2018-11-22              189.2             189.2
278 2018-11-23              225.9             225.9
279 2018-11-24              223.1             223.1
280 2018-11-25              204.0             204.0
281 2018-11-26              200.6             200.6
282 2018-11-27              124.3             124.3
283 2018-11-28              133.1             133.1
284 2018-11-29              178.9             178.9
285 2018-11-30              200.8             200.8
31  2018-12-01              202.6             202.6
32  2018-12-02              161.8             161.8
33  2018-12-03               21.8              21.8
316 2019-01-10               91.4              91.4
317 2019-01-11              173.2             173.2
318 2019-01-12              187.8             187.8
319 2019-01-13              242.4             242.4

In [4]:
alarm_dataset18=pd.DataFrame()
alarm_dataset19=pd.DataFrame()
alarm_dataset20=pd.DataFrame()
alarm_dataset21=pd.DataFrame()
#var_holder={}
#for i in range(18,22):
#    i=str(i)
alarm_dataset18=form_data(alarm_dataset18,alarm_filenames18)
alarm_dataset19=form_data(alarm_dataset19,alarm_filenames19)
alarm_dataset20=form_data(alarm_dataset20,alarm_filenames20)
alarm_dataset21=form_data(alarm_dataset21,alarm_filenames21)
alarm_dataset=pd.concat([alarm_dataset18,alarm_dataset19,alarm_dataset20,alarm_dataset21])
alarm_dataset.head(7)

,Date,Device,Details,Deactivedate,Duration
607,2018-11-16 21:59:19,Plant,DelREMO is not communicating.,2018-11-17 04:20:29,06:21:10
606,2018-11-16 21:59:19,Plant,DelREMO is not communicating.,2018-11-17 04:05:21,06:06:02
604,2018-11-17 21:58:58,Plant,DelREMO is not communicating.,2018-11-18 04:05:18,06:06:20
605,2018-11-17 21:58:58,Plant,DelREMO is not communicating.,2018-11-18 04:20:26,06:21:28
603,2018-11-18 21:58:10,Plant,DelREMO is not communicating.,2018-11-19 04:05:17,06:07:07
602,2018-11-19 16:22:57,1,Phase1 Grid Voltage Low,2018-11-19 16:23:04,00:00:07
601,2018-11-19 21:56:13,Plant,DelREMO is not communicating.,2018-11-20 04:05:20,06:09:07

In [5]:
#alarm_dataset['Date']=alarm_dataset['Date'].dt.strftime('%Y-%m-%d')

In [7]:
yield_dataset.to_csv('./Combined_Solar_Dataset.csv',index=False)
alarm_dataset.to_csv('./Combined_Alarm_Dataset.csv',index=False)