In [12]:
import pandas as pd

In [13]:
weather1=pd.read_csv('history_data1.csv')
weather2=pd.read_csv('history_data2.csv')
weather3=pd.read_csv('history_data3.csv')
weather4=pd.read_csv('history_data4.csv')
weather1

,Name,Date time,Maximum Temperature,Minimum Temperature,Temperature,Wind Chill,Heat Index,Precipitation,Snow,Snow Depth,Wind Speed,Wind Direction,Wind Gust,Visibility,Cloud Cover,Relative Humidity,Conditions
0,"Patiala, PB, India",02/01/2019,20.1,9.2,14.3,NaN,NaN,1.75,NaN,NaN,14.8,188.00,NaN,3.1,67.1,72.69,"Rain, Partially cloudy"
1,"Patiala, PB, India",02/02/2019,19.7,7.1,12.4,NaN,NaN,0.00,NaN,NaN,7.6,281.82,NaN,1.8,12.0,87.22,Clear
2,"Patiala, PB, India",02/03/2019,19.2,8.1,12.3,NaN,NaN,0.00,NaN,NaN,9.4,244.11,NaN,1.6,0.0,90.05,Clear
3,"Patiala, PB, India",02/04/2019,19.5,5.1,12.1,NaN,NaN,0.00,NaN,NaN,9.4,208.83,NaN,0.8,40.7,92.22,Partially cloudy
4,"Patiala, PB, India",02/05/2019,23.1,9.7,16.2,NaN,NaN,0.00,NaN,NaN,9.4,208.89,NaN,2.0,74.2,75.57,Partially cloudy
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
237,"Patiala, PB, India",09/26/2019,32.6,25.2,28.9,NaN,39.3,27.10,NaN,NaN,7.6,182.56,NaN,4.8,49.2,80.67,"Rain, Partially cloudy"
238,"Patiala, PB, India",09/27/2019,31.3,23.1,27.3,NaN,37.6,40.83,NaN,NaN,9.4,155.88,NaN,4.9,38.0,85.61,"Rain, Partially cloudy"
239,"Patiala, PB, India",09/28/2019,32.1,23.2,26.6,NaN,38.0,28.94,NaN,NaN,22.3,181.67,NaN,4.4,52.4,86.01,"Rain, Partially cloudy"
240,"Patiala, PB, India",09/29/2019,25.9,22.1,23.7,NaN,NaN,58.59,NaN,NaN,24.1,104.83,NaN,4.3,84.7,94.87,"Rain, Overcast"
241,"Patiala, PB, India",09/30/2019,29.1,22.7,25.8,NaN,34.7,38.69,NaN,NaN,22.3,121.57,NaN,5.1,61.4,88.89,"Rain, Partially cloudy"

In [14]:
weather_data=pd.concat([weather1,weather2,weather3,weather4])
weather_data

,Name,Date time,Maximum Temperature,Minimum Temperature,Temperature,Wind Chill,Heat Index,Precipitation,Snow,Snow Depth,Wind Speed,Wind Direction,Wind Gust,Visibility,Cloud Cover,Relative Humidity,Conditions
0,"Patiala, PB, India",02/01/2019,20.1,9.2,14.3,NaN,NaN,1.75,NaN,NaN,14.8,188.00,NaN,3.1,67.1,72.69,"Rain, Partially cloudy"
1,"Patiala, PB, India",02/02/2019,19.7,7.1,12.4,NaN,NaN,0.00,NaN,NaN,7.6,281.82,NaN,1.8,12.0,87.22,Clear
2,"Patiala, PB, India",02/03/2019,19.2,8.1,12.3,NaN,NaN,0.00,NaN,NaN,9.4,244.11,NaN,1.6,0.0,90.05,Clear
3,"Patiala, PB, India",02/04/2019,19.5,5.1,12.1,NaN,NaN,0.00,NaN,NaN,9.4,208.83,NaN,0.8,40.7,92.22,Partially cloudy
4,"Patiala, PB, India",02/05/2019,23.1,9.7,16.2,NaN,NaN,0.00,NaN,NaN,9.4,208.89,NaN,2.0,74.2,75.57,Partially cloudy
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
176,"Patiala, PB, India",07/27/2021,31.1,28.0,29.1,NaN,42.5,0.10,NaN,NaN,3.7,172.57,NaN,4.0,85.3,91.20,"Rain, Overcast"
177,"Patiala, PB, India",07/28/2021,27.0,24.8,26.0,NaN,31.7,54.77,NaN,NaN,3.6,173.14,NaN,3.2,100.0,99.73,"Rain, Overcast"
178,"Patiala, PB, India",07/29/2021,29.9,25.9,27.6,NaN,38.1,6.27,NaN,NaN,3.5,213.33,NaN,3.7,91.1,92.69,"Rain, Overcast"
179,"Patiala, PB, India",07/30/2021,31.1,25.9,28.3,NaN,41.8,10.10,NaN,NaN,5.2,97.86,NaN,4.0,84.8,88.97,"Rain, Overcast"
180,"Patiala, PB, India",07/31/2021,33.7,27.0,30.3,NaN,48.0,5.00,NaN,NaN,7.0,135.50,NaN,4.0,71.5,84.89,"Rain, Partially cloudy"

In [6]:
weather_data.columns

Index(['Name', 'Date time', 'Maximum Temperature', 'Minimum Temperature',
       'Temperature', 'Wind Chill', 'Heat Index', 'Precipitation', 'Snow',
       'Snow Depth', 'Wind Speed', 'Wind Direction', 'Wind Gust', 'Visibility',
       'Cloud Cover', 'Relative Humidity', 'Conditions'],
      dtype='object')

In [15]:
weather_data.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 912 entries, 0 to 180
Data columns (total 17 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Name                 912 non-null    object
 1   Date time            912 non-null    object
 2   Maximum Temperature  912 non-null    float64
 3   Minimum Temperature  912 non-null    float64
 4   Temperature          912 non-null    float64
 5   Wind Chill           17 non-null     float64
 6   Heat Index           633 non-null    float64
 7   Precipitation        912 non-null    float64
 8   Snow                 0 non-null      float64
 9   Snow Depth           0 non-null      float64
 10  Wind Speed           912 non-null    float64
 11  Wind Direction       911 non-null    float64
 12  Wind Gust            0 non-null      float64
 13  Visibility           912 non-null    float64
 14  Cloud Cover          912 non-null    float64
 15  Relative Humidity    912 non-null    float64
 16  Conditions           912 non-null    object
dtypes: float64(14), object(3)
memory usage: 128.2+ KB

In [7]:
weather_data=weather_data.drop(columns=['Name','Wind Chill', 'Heat Index','Snow',
       'Snow Depth', 'Wind Speed', 'Wind Direction', 'Wind Gust', 'Visibility','Relative Humidity'])

In [8]:
weather_data=weather_data.rename(columns={'Date time':'Date','Maximum Temperature':'Max','Minimum Temperature':'Min','Temperature':'Temp','Precipitation':'Prcp'})
weather_data

           Date   Max   Min  Temp   Prcp  Cloud Cover              Conditions
0    02/01/2019  20.1   9.2  14.3   1.75         67.1  Rain, Partially cloudy
1    02/02/2019  19.7   7.1  12.4   0.00         12.0                   Clear
2    02/03/2019  19.2   8.1  12.3   0.00          0.0                   Clear
3    02/04/2019  19.5   5.1  12.1   0.00         40.7        Partially cloudy
4    02/05/2019  23.1   9.7  16.2   0.00         74.2        Partially cloudy
..          ...   ...   ...   ...    ...          ...                     ...
176  07/27/2021  31.1  28.0  29.1   0.10         85.3          Rain, Overcast
177  07/28/2021  27.0  24.8  26.0  54.77        100.0          Rain, Overcast
178  07/29/2021  29.9  25.9  27.6   6.27         91.1          Rain, Overcast
179  07/30/2021  31.1  25.9  28.3  10.10         84.8          Rain, Overcast
180  07/31/2021  33.7  27.0  30.3   5.00         71.5  Rain, Partially cloudy

[912 rows x 7 columns]

In [9]:
weather_data['Date']=pd.to_datetime(weather_data['Date'])
#weather_data['Date']=weather_data['Date'].dt.strftime('%Y-%d-%m')
weather_data['Date']=weather_data['Date'].dt.strftime('%Y-%m-%d')
weather_data.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 912 entries, 0 to 180
Data columns (total 7 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Date         912 non-null    object
 1   Max          912 non-null    float64
 2   Min          912 non-null    float64
 3   Temp         912 non-null    float64
 4   Prcp         912 non-null    float64
 5   Cloud Cover  912 non-null    float64
 6   Conditions   912 non-null    object
dtypes: float64(5), object(2)
memory usage: 57.0+ KB

In [10]:
weather_data

           Date   Max   Min  Temp   Prcp  Cloud Cover              Conditions
0    2019-02-01  20.1   9.2  14.3   1.75         67.1  Rain, Partially cloudy
1    2019-02-02  19.7   7.1  12.4   0.00         12.0                   Clear
2    2019-02-03  19.2   8.1  12.3   0.00          0.0                   Clear
3    2019-02-04  19.5   5.1  12.1   0.00         40.7        Partially cloudy
4    2019-02-05  23.1   9.7  16.2   0.00         74.2        Partially cloudy
..          ...   ...   ...   ...    ...          ...                     ...
176  2021-07-27  31.1  28.0  29.1   0.10         85.3          Rain, Overcast
177  2021-07-28  27.0  24.8  26.0  54.77        100.0          Rain, Overcast
178  2021-07-29  29.9  25.9  27.6   6.27         91.1          Rain, Overcast
179  2021-07-30  31.1  25.9  28.3  10.10         84.8          Rain, Overcast
180  2021-07-31  33.7  27.0  30.3   5.00         71.5  Rain, Partially cloudy

[912 rows x 7 columns]

In [11]:
weather_data.to_csv('./weather_data.csv',index=False)